# Generated by Django 2.2.24 on 2021-06-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applessons.Applessons'),
        ),
    ]
