# Generated by Django 2.2.24 on 2021-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lessons', models.CharField(max_length=70)),
                ('teacher_name', models.CharField(max_length=80)),
            ],
        ),
    ]
